name: 'Workflow Evento'
description: 'Adiciona um coment치rio a um issue ou pull request'
inputs:
  GITHUB_TOKEN:
    description: 'Token do GitHub'
    required: true
  issue-id:
    description: 'ID do issue ou pull request'
    required: true
  comment:
    description: 'Coment치rio a ser adicionado'
    required: true
outputs:
  comment-id:
    description: 'ID do coment치rio criado'
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Adicionando coment치rio
      run: main.sh
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        ISSUE_ID: ${{ inputs.issue-id }}
        COMMENT: ${{ inputs.comment }}
